name: Chrome Docker

on:
 workflow_dispatch:
 push:
   branches:
    - master

jobs:
  # run Chrome inside a Docker container
  chrome:
    runs-on: ubuntu-latest
    # https://github.com/cypress-io/cypress-docker-images
    container: cypress/browsers:node12.18.3-chrome87-ff82
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Chrome
        uses: cypress-io/github-action@v2
        timeout-minutes: 10
        with:
          build: npm run build
          start: npm start
          browser: chrome
